In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


In [3]:
df=pd.read_csv("vocal_gender_features_new.csv")

In [4]:
df["label"].value_counts()


label
1    10380
0     5768
Name: count, dtype: int64

In [5]:
df.drop_duplicates(inplace=True)


In [ ]:
df

In [6]:
df.shape

(15070, 44)

In [7]:
df["label"].value_counts()


label
1    9841
0    5229
Name: count, dtype: int64

In [8]:
skew_vals = df.skew()
high_skew_cols = skew_vals[skew_vals.abs() > 0.75]
print(high_skew_cols)


mean_spectral_contrast    -0.899611
min_pitch                  4.878715
max_pitch                -13.400446
std_pitch                 -1.434120
spectral_kurtosis          1.478030
mfcc_8_std                 0.989087
dtype: float64


In [9]:
df['mfcc_8_std'] = np.sqrt(df['mfcc_8_std'])
df['mean_spectral_contrast'] = df['mean_spectral_contrast'] ** 2
df['min_pitch'] = np.log1p(df['min_pitch'] - df['min_pitch'].min() + 1)
df['spectral_kurtosis'] = np.log1p(df['spectral_kurtosis'] - df['spectral_kurtosis'].min() + 1)
df['max_pitch'] = df['max_pitch'] ** 3
df['std_pitch'] = df['std_pitch'] ** 3


In [10]:
X = df.drop("label", axis=1)
y = df["label"]


In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


random forest

In [13]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",   # 🔥 handles imbalance
    random_state=42
)

rf.fit(X_train_scaled, y_train)


RandomForestClassifier(class_weight='balanced', n_estimators=300,
                       random_state=42)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = rf.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.9943596549435966

Classification Report:

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      1046
           1       0.99      1.00      1.00      1968

    accuracy                           0.99      3014
   macro avg       1.00      0.99      0.99      3014
weighted avg       0.99      0.99      0.99      3014


Confusion Matrix:

[[1032   14]
 [   3 1965]]


In [15]:
importances = pd.Series(rf.feature_importances_, index=X.columns)

# Sort descending
importances = importances.sort_values(ascending=False)

# Get top 20
top_20_features = importances.head(20)

print(top_20_features)

mfcc_5_mean               0.157856
mean_spectral_contrast    0.098536
mfcc_3_std                0.087291
mfcc_2_mean               0.073235
std_spectral_bandwidth    0.050529
mfcc_12_mean              0.046632
mfcc_1_mean               0.039390
mfcc_2_std                0.032461
mfcc_10_mean              0.031611
rms_energy                0.030986
mfcc_10_std               0.025872
mfcc_6_mean               0.024496
mfcc_8_mean               0.023265
mfcc_4_mean               0.022135
mfcc_13_mean              0.020578
mfcc_7_mean               0.020561
mfcc_3_mean               0.016078
mfcc_8_std                0.014437
mfcc_11_mean              0.014035
mfcc_5_std                0.013973
dtype: float64


MFCC features capture:

Timbre

Vocal tract characteristics

Resonance patterns

Gender differences are not just pitch — they are also:

Vocal tract length

Harmonic structure

Frequency envelope shape

So model is learning deeper acoustic structure

svm

In [16]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [17]:
svm = SVC(
    kernel="rbf", 
    class_weight="balanced",
    probability=True,
    random_state=42
)

svm.fit(X_train_scaled, y_train)


SVC(class_weight='balanced', probability=True, random_state=42)

In [18]:
y_pred_svm = svm.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_svm))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_svm))


Accuracy: 0.9993364299933643

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1046
           1       1.00      1.00      1.00      1968

    accuracy                           1.00      3014
   macro avg       1.00      1.00      1.00      3014
weighted avg       1.00      1.00      1.00      3014


Confusion Matrix:

[[1045    1]
 [   1 1967]]


svm cross validation

In [19]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(svm, X_train_scaled, y_train, cv=5)

print("Cross-validation accuracy:", scores)
print("Mean CV accuracy:", scores.mean())


Cross-validation accuracy: [0.99875622 0.99958523 0.99958523 0.99958523 0.99792617]
Mean CV accuracy: 0.9990876187292488


logistic regression

In [20]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    class_weight="balanced",
    max_iter=1000
)

lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lr))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_lr))


Accuracy: 0.9913735899137359

Classification Report:

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1046
           1       1.00      0.99      0.99      1968

    accuracy                           0.99      3014
   macro avg       0.99      0.99      0.99      3014
weighted avg       0.99      0.99      0.99      3014


Confusion Matrix:

[[1039    7]
 [  19 1949]]


mlp classifier

In [21]:
from sklearn.neural_network import MLPClassifier
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [22]:
sample_weights = compute_sample_weight(
    class_weight="balanced",
    y=y_train
)


In [23]:
mlp = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation='relu',
    solver='adam',
    max_iter=500,
    random_state=42
)


In [24]:
mlp.fit(X_train_scaled, y_train, sample_weight=sample_weights)


MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=500, random_state=42)

In [25]:
y_pred_mlp = mlp.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_mlp))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_mlp))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_mlp))


Accuracy: 0.9986728599867286

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1046
           1       1.00      1.00      1.00      1968

    accuracy                           1.00      3014
   macro avg       1.00      1.00      1.00      3014
weighted avg       1.00      1.00      1.00      3014


Confusion Matrix:

[[1045    1]
 [   3 1965]]


xgboost

In [26]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Calculate imbalance ratio
scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1])

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

xgb.fit(X_train_scaled, y_train)

y_pred_xgb = xgb.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))
print(confusion_matrix(y_test, y_pred_xgb))


c:\Users\ADMIN\Desktop\human voice recognition\human\Lib\site-packages\xgboost\training.py:200: UserWarning: [15:15:40] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Accuracy: 0.9953550099535501
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1046
           1       1.00      1.00      1.00      1968

    accuracy                           1.00      3014
   macro avg       0.99      1.00      0.99      3014
weighted avg       1.00      1.00      1.00      3014

[[1040    6]
 [   8 1960]]


light gbm

In [27]:
from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(
    n_estimators=300,
    class_weight='balanced',
    random_state=42
)

lgbm.fit(X_train_scaled, y_train)



[LightGBM] [Info] Number of positive: 7873, number of negative: 4183
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004719 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10965
[LightGBM] [Info] Number of data points in the train set: 12056, number of used features: 43
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain

LGBMClassifier(class_weight='balanced', n_estimators=300, random_state=42)

In [28]:
y_pred_lgbm = lgbm.predict(X_test_scaled)
y_prob_lgbm = lgbm.predict_proba(X_test_scaled)[:,1]


c:\Users\ADMIN\Desktop\human voice recognition\human\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\ADMIN\Desktop\human voice recognition\human\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


In [29]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_lgbm))
print("Accuracy:", accuracy_score(y_test, y_pred_lgbm))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1046
           1       1.00      1.00      1.00      1968

    accuracy                           1.00      3014
   macro avg       1.00      1.00      1.00      3014
weighted avg       1.00      1.00      1.00      3014

Accuracy: 0.9970139349701393


WITH TOP 20 FEATURES

In [30]:
selected_features = [
    "mfcc_5_mean",
    "mean_spectral_contrast",
    "mfcc_3_std",
    "mfcc_2_mean",
    "std_spectral_bandwidth",
    "mfcc_12_mean",
    "mfcc_1_mean",
    "mfcc_2_std",
    "mfcc_10_mean",
    "rms_energy",
    "mfcc_10_std",
    "mfcc_6_mean",
    "mfcc_8_mean",
    "mfcc_4_mean",
    "mfcc_13_mean",
    "mfcc_7_mean",
    "mfcc_3_mean",
    "mfcc_8_std",
    "mfcc_11_mean",
    "mfcc_5_std"
]

X_top20 = X[selected_features]


In [31]:
from sklearn.model_selection import train_test_split

X_train_20, X_test_20, y_train, y_test = train_test_split(
    X_top20,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


In [32]:
from sklearn.preprocessing import StandardScaler

scaler_20 = StandardScaler()

X_train_20_scaled = scaler_20.fit_transform(X_train_20)
X_test_20_scaled = scaler_20.transform(X_test_20)


svm top 20

In [33]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

svm_20 = SVC(kernel="rbf", class_weight="balanced")

svm_20.fit(X_train_20_scaled, y_train)

y_pred_20 = svm_20.predict(X_test_20_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_20))
print(classification_report(y_test, y_pred_20))
print(confusion_matrix(y_test, y_pred_20))


Accuracy: 0.9990046449900465
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1046
           1       1.00      1.00      1.00      1968

    accuracy                           1.00      3014
   macro avg       1.00      1.00      1.00      3014
weighted avg       1.00      1.00      1.00      3014

[[1045    1]
 [   2 1966]]


Reducing from 40+ features → 20 features:

 Did NOT hurt performance
 Maintained balanced recall
 Maintained near-perfect accuracy
 Reduced model complexity
 Reduced UI input size

In [34]:
import os

os.makedirs("models")


In [35]:
import joblib

joblib.dump(svm_20, "models/svm_20.pkl")
joblib.dump(scaler_20, "models/scaler_20.pkl")
joblib.dump(selected_features, "models/selected_features.pkl")



['models/selected_features.pkl']

In [36]:
import joblib


joblib.dump(selected_features, "models/top_20_features.pkl")

['models/top_20_features.pkl']

In [39]:
X_top20 = X[selected_features]


In [40]:
X_top20.to_csv("X_top20.csv", index=False)

In [41]:
y.to_csv("y.csv",index=False)